from __future__ import annotations

import datetime as _dt

import pytest

from examples.education.identity import EducationIdentityResolver
from orchid_ai.core.events.job import JobStatus
from orchid_ai.core.events.signal import SignalEnvelope
from orchid_ai.core.events.store import OrchidScheduleRecord


@pytest.mark.asyncio
async def test_weekly_quiz_fires_and_completes(tmp_path, education_events, build_event_runtime) -> None:
    resolver = EducationIdentityResolver()

    async def _invoker(run, auth) -> dict:
        return {
            "final_response": (
                f"Weekly quiz generated by {auth.extra.get('service_account', '<missing>')}.\n"
                f"{run.spec.prompt}"
            ),
            "agents_used": ["quiz-generator"],
        }

    runtime = await build_event_runtime(
        tmp_path,
        trigger_ids=["weekly-quiz"],
        resolver=resolver,
        invoker=_invoker,
        db_name="education-scheduled.db",
    )
    try:
        schedule = next(schedule for schedule in education_events.schedules if schedule.id == "weekly-quiz-cron")
        await runtime["storage"].schedules.upsert(
            OrchidScheduleRecord(
                schedule_id=schedule.id,
                trigger_id=schedule.trigger_id,
                cron=schedule.cron,
                interval_seconds=schedule.interval_seconds,
                identity_claim=schedule.identity.model_dump(),
                last_fire_at=None,
                next_fire_at=None,
                enabled=schedule.enabled,
            )
        )

        fire_iso = "2026-05-25T08:00:00+00:00"
        await runtime["dispatcher"].ingest(
            SignalEnvelope(
                type="cron",
                payload={"schedule_id": schedule.id, "fire_time": fire_iso},
                source=f"scheduler:{schedule.id}",
                occurred_at=_dt.datetime.fromisoformat(fire_iso),
                tenant_key="education-demo",
                identity_claim={"mode": "service_account", "name": "quiz-bot"},
                dedupe_key=f"{schedule.id}:{fire_iso}",
            )
        )

        await runtime["processor"].process_until_idle(
            queue=runtime["queue"],
            signal_store=runtime["storage"].signals,
            triggers=runtime["registry"],
            identity_resolver=resolver,
            job_store=runtime["storage"].jobs,
            job_runner=runtime["runner"],
        )

        runs = await runtime["storage"].jobs.list()
        assert len(runs) == 1
        [run] = runs
        assert run.status == JobStatus.SUCCEEDED
        assert run.spec.trigger_id == "weekly-quiz"
        assert run.spec.visibility == "tenant"
        assert run.spec.visibility_user_id is None
        assert "quiz-bot" in (run.result or {}).get("final_response", "")
        assert "Generate a weekly review quiz" in (run.result or {}).get("final_response", "")
    finally:
        await runtime["close"]()
